// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy_Ecr73IGInBTd1yOX2gv5pCGXROORYo',
    appId: '1:1098182535825:web:b7b9786371c2b7de92ed30',
    messagingSenderId: '1098182535825',
    projectId: 'noted-d085f',
    authDomain: 'noted-d085f.firebaseapp.com',
    storageBucket: 'noted-d085f.appspot.com',
    measurementId: 'G-K5XFBG4QD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIH5PUSX_oHWQYsDpWHIKSaaABim9s6Q0',
    appId: '1:1098182535825:android:290f51d8084d544f92ed30',
    messagingSenderId: '1098182535825',
    projectId: 'noted-d085f',
    storageBucket: 'noted-d085f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIfWFyAgytG9rjtcXkFJQvyum7SrK6Ajc',
    appId: '1:1098182535825:ios:7c3f22211c526fbc92ed30',
    messagingSenderId: '1098182535825',
    projectId: 'noted-d085f',
    storageBucket: 'noted-d085f.appspot.com',
    iosBundleId: 'com.example.todosPractise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIfWFyAgytG9rjtcXkFJQvyum7SrK6Ajc',
    appId: '1:1098182535825:ios:5de8dc4f93abd8e592ed30',
    messagingSenderId: '1098182535825',
    projectId: 'noted-d085f',
    storageBucket: 'noted-d085f.appspot.com',
    iosBundleId: 'com.example.todosPractise.RunnerTests',
  );
}
